### PR TITLE
Added architecture design diagrams

### PR DESCRIPTION
**Pull request by AAndova**

### CODE REVIEW

**Comment by andrejdaskalov** [comment]
Commitnite go i mockup pa ke merge 
You shall not pass

**Review by andrejdaskalov — CHANGES_REQUESTED** [review]
mockup

**Review by marijagjorgjieva — CHANGES_REQUESTED** [review]
_Уште мокапот да се додади :D_ 💃🏻🕺🏻
Fali mockup

**Review by marijagjorgjieva — APPROVED** [review]
**_LOOKS VERY GOOD TO ME_** 😘😘😘😘

**Review by andrejdaskalov — APPROVED** [review]

**Pull request merged**
